include: package:solid_lints/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true


custom_lint:
  rules:
    - member_ordering:
      order:
        - fields
        - getters_setters
        - constructors
        - methods
      widgets_order:
        - init_state_method
        - did_change_dependencies_method
        - did_update_widget_method
        - deactivate_method
        - dispose_method
        - build_method

linter:
  rules:
    avoid_positional_boolean_parameters: false
