name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Package, Tests, and Example
        run: bash tool/analyze.sh

      - name: Check Dart Code Linter Rules
        run: dart run dart_code_linter:metrics analyze lib test example/lib --fatal-style --fatal-performance

      - name: Run Tests
        run: flutter test --no-pub
